spring:
  application:
    name: 'produtor'
  datasource:
    username: root 
    password: 123456
    url: jdbc:mysql://localhost:3306/produtor
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
  servlet:
    context-path: /produtor
  